name: API Reference

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime 7.8.0 --quiet
        haxelib install openfl 8.9.7 --quiet
        haxelib install actuate --quiet
        haxelib install dox --quiet
        haxelib dev feathersui $GITHUB_WORKSPACE
    - name: Build API reference
      working-directory: docs
      run: haxe docs.hxml
    - uses: actions/upload-artifact@v2
      with:
        name: feathersui-openfl-docs
        path: build/api/
        if-no-files-found: error
    - name: Deploy to unstable
      if: ${{ github.event_name != 'pull_request' }}
      uses: garygrossgarten/github-action-scp@release
      with:
        local: build/api
        remote: api.feathersui.com/unstable
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}