name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test-neko:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime 7.8.0 --quiet
        haxelib install openfl 8.9.7 --quiet
        haxelib install actuate --quiet
        haxelib install utest --quiet
        haxelib dev feathersui $GITHUB_WORKSPACE
    - name: Run Tests
      working-directory: test
      run: haxelib run openfl test neko